version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          mapping: |
            .*\.md1        first_condition true
            .*\.md2        first_condition false
          config-path: .circleci/workflows.yml
