version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          filters:
            tags:
              only: /^.*$/
          base-revision: main
          mapping: |
            src/.*  first_condition true
            .*      second_condition true
            .*      second_condition false
          config-path: .circleci/workflows.yml
