version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          filters:
            tags:
              only: /^.*$/
          base-revision: main
          mapping: |
            .*\.yml                first_condition true
            .*\.(?!(yml)$)([^.]+$) first_condition false
          config-path: .circleci/workflows.yml
