version: 2.1

parameters:
  first_condition:
    type: boolean
    default: false

  second_condition:
    type: boolean
    default: false

executors:
  build:
    docker:
      - image: cimg/base:2021.04

jobs:
  sanity:
    docker:
      # next-gen ubuntu image
      - image: cimg/base:2021.04
    steps:
      - run: echo "Running sanity"

  echo_a:
    executor: build
    description: A
    steps:
      - run: echo "A"

  echo_b:
    executor: build
    description: B
    steps:
      - run: echo "B"

workflows:
  do_1:
    when: << pipeline.parameters.second_condition >>
    jobs:
      - sanity: &filters-always
          filters:
            tags:
              only: /^.*$/
      - echo_a:
          <<: *filters-always
          requires:
            - sanity

  do_2:
    when:
      not: << pipeline.parameters.second_condition >>
    jobs:
      - sanity:
          <<: *filters-always
      - echo_b:
          <<: *filters-always
          requires:
            - sanity
